//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilenioCloudModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colegio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Colegio()
        {
            this.Colegio_Usuario = new HashSet<Colegio_Usuario>();
        }
    
        public System.Guid Codigo_Id { get; set; }
        public int Nit { get; set; }
        public string Nombre { get; set; }
        public int CodigoColegio { get; set; }
        public int CodigoDane { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FiniFiscal { get; set; }
        public System.DateTime FfinFiscal { get; set; }
        public string UbicacionGeo { get; set; }
        public string Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colegio_Usuario> Colegio_Usuario { get; set; }
    }
}
