//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilenioCloudModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colegio_Usuario
    {
        public System.Guid Colegio_Id { get; set; }
        public System.Guid Usuario_Id { get; set; }
        public string fecha_caducidad { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Colegio Colegio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
