//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilenioCloudModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poblado
    {
        public Nullable<System.Guid> Codigo_Id { get; set; }
        public string Municipio_Id { get; set; }
        public string Poblado_Id { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
